[package]
name = "cumulus-client-collator"
version = "0.18.0"
authors.workspace = true
edition.workspace = true
description = "Common node-side functionality and glue code to collate parachain blocks."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
parking_lot = { workspace = true, default-features = true }
codec = { features = ["derive"], workspace = true, default-features = true }
futures = { workspace = true }
tracing = { workspace = true, default-features = true }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
polkadot-node-primitives = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
polkadot-node-subsystem = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
polkadot-overseer = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
cumulus-client-network = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", tag = "polkadot-stable2409", default-features = true }

[dev-dependencies]
async-trait = { workspace = true }

# Substrate
sp-maybe-compressed-blob = { default-features = true, path = "../../../substrate/primitives/maybe-compressed-blob" }
sp-state-machine = { default-features = true, path = "../../../substrate/primitives/state-machine" }
sp-tracing = { default-features = true, path = "../../../substrate/primitives/tracing" }

# Polkadot
polkadot-node-subsystem-test-helpers = { path = "../../../polkadot/node/subsystem-test-helpers" }

# Cumulus
cumulus-test-client = { path = "../../test/client" }
cumulus-test-runtime = { path = "../../test/runtime" }
cumulus-test-relay-sproof-builder = { default-features = true, path = "../../test/relay-sproof-builder" }
